// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#include "NativeSandboxManager.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeSandboxManager::NativeSandboxManager() : ::djinni::JniInterface<::helloworld::SandboxManager, NativeSandboxManager>() {}

NativeSandboxManager::~NativeSandboxManager() = default;

NativeSandboxManager::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeSandboxManager::JavaProxy::~JavaProxy() = default;

std::string NativeSandboxManager::JavaProxy::get_sandbox_path() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeSandboxManager>::get();
    auto jret = (jstring)jniEnv->CallObjectMethod(Handle::get().get(), data.method_getSandboxPath);
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::String::toCpp(jniEnv, jret);
}

}  // namespace djinni_generated
