// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

package com.ringcentral.helloworld;

public abstract class SandboxManager {
    public abstract String getSandboxPath();
}
