// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#import <Foundation/Foundation.h>
@class HWHelloWorld;
@protocol HWSandboxManager;


@interface HWHelloWorld : NSObject

+ (nullable HWHelloWorld *)create;

+ (nullable HWHelloWorld *)createWithSandboxManager:(nullable id<HWSandboxManager>)sandboxManager;

- (nonnull NSString *)getHelloWorld;

- (nonnull NSString *)getSandboxPath;

@end
