// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#include "sandbox_manager.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol HWSandboxManager;

namespace djinni_generated {

class SandboxManager
{
public:
    using CppType = std::shared_ptr<::helloworld::SandboxManager>;
    using CppOptType = std::shared_ptr<::helloworld::SandboxManager>;
    using ObjcType = id<HWSandboxManager>;

    using Boxed = SandboxManager;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

