// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#pragma once

#include <memory>
#include <string>

namespace helloworld {

class SandboxManager;

class HelloWorld {
public:
    virtual ~HelloWorld() {}

    static std::shared_ptr<HelloWorld> create();

    static std::shared_ptr<HelloWorld> createWithSandboxManager(const std::shared_ptr<SandboxManager> & sandboxManager);

    virtual std::string get_hello_world() = 0;

    virtual std::string get_sandbox_path() = 0;
};

}  // namespace helloworld
