// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#pragma once

#include <string>

namespace helloworld {

class SandboxManager {
public:
    virtual ~SandboxManager() {}

    virtual std::string get_sandbox_path() = 0;
};

}  // namespace helloworld
